// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Tepeyac.UI.Cocoa {
	
	
	// Should subclass MonoMac.AppKit.NSStatusItem
	[MonoMac.Foundation.Register("StatusItemBurritoDayView")]
	public partial class StatusItemBurritoDayView {
	}
	
	// Should subclass MonoMac.AppKit.NSViewController
	[MonoMac.Foundation.Register("StatusItemBurritoDayViewController")]
	public partial class StatusItemBurritoDayViewController {
	}
}
